### PR TITLE
404 Page Added and Routes Functionality updated

### LINKED ISSUE #31: [BUG]: No 404 Page on Invalid URL just a blank page
## Description

When I navigate to some unknown url (ex: https://js-intl-kitchen-sink.netlify.com/abc)

Netlify default Not Found page
image

### Steps to reproduce

Navigate to a route that doesn't exist

### Expected result

You should see a beautiful 404 Page

image

### Actual result

What happened.
image

### PR DESCRIPTION
**Pull request by harshanarisetty**
Relates to #31 
Fixes #31 

- 404 Component was built 
- Switch condition added to the App.js Routes so that only one route is valid at any time
- Any wrong url will now be pushed to the 404 Component

## Screenshots (if visual changes)
Screen Shot 2019-10-14 at 5 51 01 PM

## Proposed Changes

  -
  -
  -

### CODE REVIEW

**Review by luisFilipePT — DISMISSED** [review]
we are using `css modules` in this project and only regular css for global styles

`import styles from './styles.modules.css'`

Check the footer component on an example implementation

We will finish the review after the requested change but the rest seems good 🏅

**Review by harshanarisetty — COMMENTED** [review]
I have made changes to the css to css modules you may merge if you feel that's good

File: src/components/404/index.js [hunk 1]
```diff
@@ -0,0 +1,22 @@
+import React, { Component } from 'react';
+import { Link } from 'react-router-dom';
+import NotFoundImg from '../../assets/images/404.svg';
+import styles from './styles.module.css';
+export default class NoMatch extends Component {
```
Comment (luisFilipePT) [inline src/components/404/index.js]: Would you mind 🙏 changing this to a functional approach since its the approach used in all the codebase (and the latest version of React allow us to do it)
ex:
```
const NoMatch = () => (
<div>...</div>
);

export default NoMatch;
```
So far I think that if you look through all the project you don't find a single `class` 🤔 😄

**Comment by luisFilipePT** [comment]
> I have made changes to the css to css modules you may merge if you feel that's good

Yes, that part is fine 👍 , thanks

**Comment by harshanarisetty** [comment]
Changes made to 404 component from class to  functional approach

**Review by luisFilipePT — APPROVED** [review]
You don't even needed the `return` keyword on the NoMatch component 😎 

Nice job 💯

**Comment by luisFilipePT** [comment]
@all-contributors please add @harshanarisetty i for code
